imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-core
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-seo
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
