baseURL = "https://adarshkrishnan.com/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-PaperMod"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 3

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/kriashks"
  weight = 4
