name: Build & deploy Hugo site
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      target:
        description: "Where to deploy (pages | s3)"
        default: "pages"
        required: false
      hugo:
        description: "Hugo version tag, e.g. v0.147.9"
        default: "v0.147.9"
        required: false

jobs:
# ------------------------------------------------------
# 1. Build once – outputs ./public as an artefact
# ------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    outputs:
      publish-dir: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0          # needed for .GitInfo etc.

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'
          extended: true      # PaperMod theme requires extended version

      - name: Build site
        run: hugo --minify

      - name: Upload artefact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public

# ------------------------------------------------------
# 2a. Default route – publish to GitHub Pages
# ------------------------------------------------------
  deploy-pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' &&
        (github.event.inputs.target == '' || github.event.inputs.target == 'pages')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
